"""fix invitation

Revision ID: 02b4a4d209d8
Revises: f10c5c819256
Create Date: 2026-05-27 15:35:47.226027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '02b4a4d209d8'
down_revision: Union[str, Sequence[str], None] = 'f10c5c819256'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_invitations', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_invitations', sa.Column('role', postgresql.ENUM('ADMIN', 'LEADER', 'MEMBER', 'NONE', name='invite_role'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
