"""fix project fields

Revision ID: 0770aca007a6
Revises: a0f16903d18c
Create Date: 2026-05-07 21:19:09.334179

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "0770aca007a6"
down_revision: Union[str, Sequence[str], None] = "a0f16903d18c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "projects",
        "id",
        existing_type=sa.INTEGER(),
        type_=sa.UUID(),
        existing_nullable=False,
    )
    op.alter_column("projects", "created_by", existing_type=sa.UUID(), nullable=True)
    op.alter_column("projects", "advisor", existing_type=sa.UUID(), nullable=True)
    op.alter_column("projects", "instructor", existing_type=sa.UUID(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("projects", "instructor", existing_type=sa.UUID(), nullable=False)
    op.alter_column("projects", "advisor", existing_type=sa.UUID(), nullable=False)
    op.alter_column("projects", "created_by", existing_type=sa.UUID(), nullable=False)
    op.alter_column(
        "projects",
        "id",
        existing_type=sa.UUID(),
        type_=sa.INTEGER(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
