"""add health_status on project_snapshot

Revision ID: 0fb5172497a2
Revises: b7d24b824503
Create Date: 2026-05-15 20:04:30.246175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fb5172497a2'
down_revision: Union[str, Sequence[str], None] = 'b7d24b824503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_snapshots', sa.Column('health_status', sa.Enum('GOOD', 'WARNING', 'BAD', name='healt_status'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_snapshots', 'health_status')
    # ### end Alembic commands ###
