"""add message

Revision ID: 1fd018f393ab
Revises: 8a5c3110d9eb
Create Date: 2026-09-08 21:50:05.579598

"""
from typing import Sequence, Union


from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '1fd018f393ab'
down_revision: Union[str, Sequence[str], None] = '8a5c3110d9eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_messages_project_created', 'messages', ['project_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_messages_project_id'), 'messages', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_project_id'), table_name='messages')
    op.drop_index('ix_messages_project_created', table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
