"""fix paper table

Revision ID: 337c6f25640b
Revises: aa3da551f0d2
Create Date: 2026-10-08 14:35:14.037509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '337c6f25640b'
down_revision: Union[str, Sequence[str], None] = 'aa3da551f0d2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('embedding_status', sa.String(length=20), server_default='pending', nullable=False))
    op.create_index(op.f('ix_papers_embedding_status'), 'papers', ['embedding_status'], unique=False)
    op.drop_column('papers', 'adviser')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('adviser', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_papers_embedding_status'), table_name='papers')
    op.drop_column('papers', 'embedding_status')
    # ### end Alembic commands ###
