"""update project fields

Revision ID: 4f838b5ed2ed
Revises: 322d4facc016
Create Date: 2026-05-07 09:23:09.648768

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4f838b5ed2ed"
down_revision: Union[str, Sequence[str], None] = "6c1edaf4d7f6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("projects", sa.Column("description", sa.String(), nullable=False))
    op.alter_column("projects", "created_by", existing_type=sa.UUID(), nullable=True)
    op.alter_column("projects", "advisor", existing_type=sa.UUID(), nullable=True)
    op.alter_column("projects", "instructor", existing_type=sa.UUID(), nullable=True)
    op.alter_column(
        "projects", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.alter_column(
        "projects", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=True
    )
    op.drop_column("projects", "descrption")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "projects",
        sa.Column("descrption", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.alter_column(
        "projects", "updated_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column(
        "projects", "created_at", existing_type=postgresql.TIMESTAMP(), nullable=False
    )
    op.alter_column("projects", "instructor", existing_type=sa.UUID(), nullable=False)
    op.alter_column("projects", "advisor", existing_type=sa.UUID(), nullable=False)
    op.alter_column("projects", "created_by", existing_type=sa.UUID(), nullable=False)
    op.drop_column("projects", "description")
    # ### end Alembic commands ###
