"""initial migration

Revision ID: 52d8277c27f2
Revises:
Create Date: 2026-08-07 20:02:50.359973

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = "52d8277c27f2"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("first_name", sa.String(length=150), nullable=False),
        sa.Column("last_name", sa.String(length=150), nullable=False),
        sa.Column(
            "role",
            sa.Enum("ADMIN", "STUDENT", "INSTRUCTOR", name="user_role"),
            nullable=False,
        ),
        sa.Column("id", fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("hashed_password", sa.String(length=1024), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("is_verified", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "projects",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("advisor", sa.UUID(), nullable=True),
        sa.Column("instructor", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["advisor"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["instructor"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("sender_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(), nullable=False),
        sa.Column(
            "role",
            sa.Enum("LEADER", "ADVISOR", "MEMBER", "INSTRUCTOR", name="invited_role"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "ACCEPTED", "REJECTED", name="invite_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["sender_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column(
            "project_role",
            sa.Enum("leader", "advisor", "member", "instructor", name="projectrole"),
            nullable=True,
        ),
        sa.Column(
            "skills",
            sa.Enum(
                "Backend Development",
                "Frontend Development",
                "Mobile Development",
                "IOT Development",
                "Database Design",
                "System Architecture",
                "UI/UX Design",
                "Testing and Quality Assurance",
                "Literature Review",
                "Data Collection",
                "Survey and Questionnaire Design",
                "Interview and Observation",
                "Data Analysis",
                "Technical Writing",
                "Documentation",
                "Diagram and Modeling",
                "Editing and Proofreading",
                "Financial Documentation",
                "Budget Planning ",
                "Resource Management",
                name="member_skills",
            ),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "project_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("total_workload_points", sa.Integer(), nullable=False),
        sa.Column("avg_workload", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("progress_score", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("progress_percentage", sa.Integer(), nullable=False),
        sa.Column("expected_score", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column("expected_percentage", sa.Integer(), nullable=False),
        sa.Column(
            "schedule_variance", sa.Numeric(precision=10, scale=2), nullable=False
        ),
        sa.Column("workload_balance", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column(
            "imbalance_severity",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="severity"),
            nullable=False,
        ),
        sa.Column("health_score", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "health_status",
            sa.Enum("GOOD", "WARNING", "BAD", name="health_status"),
            nullable=False,
        ),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "project_id", "snapshot_date", name="uq_project_snapshot_date"
        ),
    )
    op.create_table(
        "redistribution_recommendations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column(
            "suggestion_type",
            sa.Enum("SHARE", "SPLIT", "TRANSFER", "RESCHEDULE", name="type"),
            nullable=False,
        ),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("expected_workload_after", sa.Text(), nullable=False),
        sa.Column("deadline_impact", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "supertasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "tasks",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("started_at", sa.Date(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "NOT_STARTED", "IN_PROGRESS", "SUBMITTED", "COMPLETED", name="status"
            ),
            nullable=True,
        ),
        sa.Column(
            "complexity",
            sa.Enum("LOW", "MEDIUM", "HIGH", name="complexity"),
            nullable=True,
        ),
        sa.Column(
            "priority", sa.Enum("LOW", "MEDIUM", "HIGH", name="priority"), nullable=True
        ),
        sa.Column("complexity_points", sa.Integer(), nullable=True),
        sa.Column(
            "category",
            sa.Enum("DOCUMENT", "RESEARCH", "DEVELOPMENT", "FINANCE", name="category"),
            nullable=True,
        ),
        sa.Column("deadline", sa.DateTime(timezone=True), nullable=True),
        sa.Column("total_time_spent", sa.Integer(), nullable=True),
        sa.Column(
            "skills_required",
            sa.Enum(
                "Backend Development",
                "Frontend Development",
                "Mobile Development",
                "IOT Development",
                "Database Design",
                "System Architecture",
                "UI/UX Design",
                "Testing and Quality Assurance",
                "Literature Review",
                "Data Collection",
                "Survey and Questionnaire Design",
                "Interview and Observation",
                "Data Analysis",
                "Technical Writing",
                "Documentation",
                "Diagram and Modeling",
                "Editing and Proofreading",
                "Financial Documentation",
                "Budget Planning ",
                "Resource Management",
                name="task_skills",
            ),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["project_id"], ["projects.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "assigned_members",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.Enum("LEADER", "MEMBER", name="role"), nullable=True),
        sa.Column("effort_share", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "member_activities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=True),
        sa.Column("detail", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"], ["project_members.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "member_snapshots",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("member_id", sa.UUID(), nullable=False),
        sa.Column("workload_points", sa.Numeric(precision=10, scale=2), nullable=False),
        sa.Column(
            "workload_status",
            sa.Enum("OK", "UNDERUTILIZED", "OVERLOADED", name="member_status"),
            nullable=False,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["member_id"], ["project_members.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column(
            "type",
            sa.Enum("PROJECT_INVITATION", "GENERAL", name="notificationtype"),
            nullable=False,
        ),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("invitation_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["invitation_id"], ["project_invitations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "peer_evaluations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("evaluator_id", sa.UUID(), nullable=True),
        sa.Column("evaluated_id", sa.UUID(), nullable=True),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("score", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluated_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["evaluator_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_comments",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("author_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_contents",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("file_name", sa.String(length=255), nullable=True),
        sa.Column("file_path", sa.String(length=255), nullable=True),
        sa.Column("file_size", sa.Integer(), nullable=True),
        sa.Column("mime_type", sa.String(length=150), nullable=True),
        sa.Column("uploaded_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_relations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("related_to", sa.UUID(), nullable=True),
        sa.Column(
            "relation",
            sa.Enum("BLOCKS", "BLOCKED_BY", "RELATED", name="relation"),
            nullable=True,
        ),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["related_to"], ["tasks.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_submissions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column(
            "result",
            sa.Enum("REVISION", "ACCEPTED", "PENDING", name="result"),
            nullable=True,
        ),
        sa.Column("comment", sa.String(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "task_tag",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_id", sa.UUID(), nullable=True),
        sa.Column("tag_id", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["task_id"], ["tasks.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("task_tag")
    op.drop_table("task_submissions")
    op.drop_table("task_relations")
    op.drop_table("task_contents")
    op.drop_table("task_comments")
    op.drop_table("peer_evaluations")
    op.drop_table("notifications")
    op.drop_table("member_snapshots")
    op.drop_table("member_activities")
    op.drop_table("assigned_members")
    op.drop_table("tasks")
    op.drop_table("supertasks")
    op.drop_table("redistribution_recommendations")
    op.drop_table("project_snapshots")
    op.drop_table("project_members")
    op.drop_table("project_invitations")
    op.drop_table("projects")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_table("tags")
    # ### end Alembic commands ###
