"""dunno

Revision ID: 569d5b5afe0c
Revises: b83031b20076
Create Date: 2026-08-25 22:56:43.013653

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '569d5b5afe0c'
down_revision: Union[str, Sequence[str], None] = 'b83031b20076'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_members', sa.Column('member_id', sa.UUID(), nullable=True))
    op.drop_constraint(op.f('assigned_members_user_id_fkey'), 'assigned_members', type_='foreignkey')
    op.create_foreign_key(None, 'assigned_members', 'project_members', ['member_id'], ['id'])
    op.drop_column('assigned_members', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assigned_members', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assigned_members', type_='foreignkey')
    op.create_foreign_key(op.f('assigned_members_user_id_fkey'), 'assigned_members', 'users', ['user_id'], ['id'])
    op.drop_column('assigned_members', 'member_id')
    # ### end Alembic commands ###
