"""remove supertask for now

Revision ID: 7a5ad3a09fe2
Revises: 452ce9dfc171
Create Date: 2026-05-13 21:50:08.193594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a5ad3a09fe2'
down_revision: Union[str, Sequence[str], None] = '452ce9dfc171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tasks_supertask_id_fkey'), 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'supertask_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('supertask_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('tasks_supertask_id_fkey'), 'tasks', 'supertasks', ['supertask_id'], ['id'])
    # ### end Alembic commands ###
