"""add message

Revision ID: 8a5c3110d9eb
Revises: 569d5b5afe0c
Create Date: 2026-09-08 02:02:44.308824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a5c3110d9eb'
down_revision: Union[str, Sequence[str], None] = '569d5b5afe0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'invitation_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notifications', 'invitation_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
