"""add project members module

Revision ID: 940dcf4a4202
Revises: 0770aca007a6
Create Date: 2026-05-11 23:00:36.962414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '940dcf4a4202'
down_revision: Union[str, Sequence[str], None] = '0770aca007a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('project_role', sa.Enum('ADMIN', 'LEADER', 'MEMBER', 'NONE', name='projectrole'), nullable=True),
    sa.Column('workload_points', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('contribution_points', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=True)
    op.drop_constraint(op.f('projects_advisor_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_instructor_fkey'), 'projects', type_='foreignkey')
    op.drop_constraint(op.f('projects_created_by_fkey'), 'projects', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(op.f('projects_created_by_fkey'), 'projects', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('projects_instructor_fkey'), 'projects', 'users', ['instructor'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('projects_advisor_fkey'), 'projects', 'users', ['advisor'], ['id'], ondelete='SET NULL')
    op.alter_column('projects', 'updated_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_table('project_members')
    # ### end Alembic commands ###
