"""fix fields

Revision ID: a0f16903d18c
Revises: 4f838b5ed2ed
Create Date: 2026-05-07 10:18:25.327077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a0f16903d18c'
down_revision: Union[str, Sequence[str], None] = '4f838b5ed2ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'created_by',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('projects', 'advisor',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('projects', 'instructor',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_foreign_key(None, 'projects', 'users', ['instructor'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'projects', 'users', ['advisor'], ['id'])
    op.drop_index(op.f('ix_user_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_user_email'), 'users', ['email'], unique=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.alter_column('projects', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('projects', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('projects', 'instructor',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('projects', 'advisor',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('projects', 'created_by',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###
