"""add workload related fields

Revision ID: a10944a318f0
Revises: 52d8277c27f2
Create Date: 2026-08-15 02:04:15.690849

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a10944a318f0'
down_revision: Union[str, Sequence[str], None] = '52d8277c27f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('member_snapshots', sa.Column('total_workload_points', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('member_snapshots', sa.Column('total_effective_points', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('member_snapshots', sa.Column('capacity_multiplier', sa.Numeric(precision=3, scale=2), nullable=False))
    op.add_column('member_snapshots', sa.Column('silence_warning', sa.Boolean(), nullable=False))
    op.add_column('member_snapshots', sa.Column('consecutive_fallback_count', sa.Integer(), nullable=False))
    op.drop_column('member_snapshots', 'workload_points')
    op.add_column('projects', sa.Column('base_days_per_point', sa.Integer(), nullable=False))
    op.add_column('projects', sa.Column('escalation_threshold', sa.Integer(), nullable=False))
    op.add_column('tasks', sa.Column('completed_at', sa.Date(), nullable=False))
    op.add_column('tasks', sa.Column('primary_skill', sa.Enum('Backend Development', 'Frontend Development', 'Mobile Development', 'IOT Development', 'Database Design', 'System Architecture', 'UI/UX Design', 'Testing and Quality Assurance', 'Literature Review', 'Data Collection', 'Survey and Questionnaire Design', 'Interview and Observation', 'Data Analysis', 'Technical Writing', 'Documentation', 'Diagram and Modeling', 'Editing and Proofreading', 'Financial Documentation', 'Budget Planning ', 'Resource Management', name='task_skills'), nullable=False))
    op.add_column('tasks', sa.Column('secondary_skills', sa.ARRAY(sa.Enum('Backend Development', 'Frontend Development', 'Mobile Development', 'IOT Development', 'Database Design', 'System Architecture', 'UI/UX Design', 'Testing and Quality Assurance', 'Literature Review', 'Data Collection', 'Survey and Questionnaire Design', 'Interview and Observation', 'Data Analysis', 'Technical Writing', 'Documentation', 'Diagram and Modeling', 'Editing and Proofreading', 'Financial Documentation', 'Budget Planning ', 'Resource Management', name='task_skills')), nullable=False))
    op.drop_column('tasks', 'skills_required')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('skills_required', postgresql.ENUM('Backend Development', 'Frontend Development', 'Mobile Development', 'IOT Development', 'Database Design', 'System Architecture', 'UI/UX Design', 'Testing and Quality Assurance', 'Literature Review', 'Data Collection', 'Survey and Questionnaire Design', 'Interview and Observation', 'Data Analysis', 'Technical Writing', 'Documentation', 'Diagram and Modeling', 'Editing and Proofreading', 'Financial Documentation', 'Budget Planning ', 'Resource Management', name='task_skills'), autoincrement=False, nullable=False))
    op.drop_column('tasks', 'secondary_skills')
    op.drop_column('tasks', 'primary_skill')
    op.drop_column('tasks', 'completed_at')
    op.drop_column('projects', 'escalation_threshold')
    op.drop_column('projects', 'base_days_per_point')
    op.add_column('member_snapshots', sa.Column('workload_points', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
    op.drop_column('member_snapshots', 'consecutive_fallback_count')
    op.drop_column('member_snapshots', 'silence_warning')
    op.drop_column('member_snapshots', 'capacity_multiplier')
    op.drop_column('member_snapshots', 'total_effective_points')
    op.drop_column('member_snapshots', 'total_workload_points')
    # ### end Alembic commands ###
