"""add categ to paper

Revision ID: aa3da551f0d2
Revises: e4c4ae2db2e9
Create Date: 2026-10-08 13:11:57.829041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'aa3da551f0d2'
down_revision: Union[str, Sequence[str], None] = 'e4c4ae2db2e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('category', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('research_problem', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('methodology', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('conclusion', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('embedding_text', sa.Text(), nullable=True))
    op.add_column('papers', sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True))
    op.create_index(op.f('ix_papers_category'), 'papers', ['category'], unique=False)
    op.create_index('ix_papers_embedding_hnsw', 'papers', ['embedding'], unique=False, postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_papers_embedding_hnsw', table_name='papers', postgresql_using='hnsw', postgresql_ops={'embedding': 'vector_cosine_ops'})
    op.drop_index(op.f('ix_papers_category'), table_name='papers')
    op.drop_column('papers', 'embedding')
    op.drop_column('papers', 'embedding_text')
    op.drop_column('papers', 'conclusion')
    op.drop_column('papers', 'methodology')
    op.drop_column('papers', 'research_problem')
    op.drop_column('papers', 'category')
    # ### end Alembic commands ###
