"""add username and fullname in users table

Revision ID: b63713578c39
Revises: c4fc19f74c78
Create Date: 2026-05-01 17:58:33.684708

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b63713578c39"
down_revision: Union[str, Sequence[str], None] = "c4fc19f74c78"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("username", sa.String(length=50), nullable=False))
    op.add_column("users", sa.Column("full_name", sa.String(length=100), nullable=True))
    op.create_unique_constraint(None, "users", ["username"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    op.drop_column("users", "full_name")
    op.drop_column("users", "username")
    # ### end Alembic commands ###
