"""fix snapshot model

Revision ID: bd28117b9f6b
Revises: 0b232c050a45
Create Date: 2026-05-17 23:18:27.402845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd28117b9f6b'
down_revision: Union[str, Sequence[str], None] = '0b232c050a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'project_snapshots', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'project_snapshots', type_='foreignkey')
    # ### end Alembic commands ###
