"""remove conclusion on paper

Revision ID: ce973cf06fb2
Revises: 337c6f25640b
Create Date: 2026-10-10 21:58:07.347379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce973cf06fb2'
down_revision: Union[str, Sequence[str], None] = '337c6f25640b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('papers', 'conclusion')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('papers', sa.Column('conclusion', sa.TEXT(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
