"""checking

Revision ID: cf0d2a096057
Revises: b65469819c1a
Create Date: 2026-09-21 23:08:23.819291

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cf0d2a096057'
down_revision: Union[str, Sequence[str], None] = 'b65469819c1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_project_id'), table_name='messages')
    op.drop_table('messages')
    op.alter_column('project_members', 'skills',
               existing_type=postgresql.ARRAY(postgresql.ENUM('Backend Development', 'Frontend Development', 'Mobile Development', 'IOT Development', 'Database Design', 'System Architecture', 'UI/UX Design', 'Testing and Quality Assurance', 'Literature Review', 'Data Collection', 'Survey and Questionnaire Design', 'Interview and Observation', 'Data Analysis', 'Technical Writing', 'Documentation', 'Diagram and Modeling', 'Editing and Proofreading', 'Financial Documentation', 'Budget Planning ', 'Resource Management', name='member_skills')),
               nullable=True,
               existing_server_default=sa.text("'{}'::member_skills[]"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('project_members', 'skills',
               existing_type=postgresql.ARRAY(postgresql.ENUM('Backend Development', 'Frontend Development', 'Mobile Development', 'IOT Development', 'Database Design', 'System Architecture', 'UI/UX Design', 'Testing and Quality Assurance', 'Literature Review', 'Data Collection', 'Survey and Questionnaire Design', 'Interview and Observation', 'Data Analysis', 'Technical Writing', 'Documentation', 'Diagram and Modeling', 'Editing and Proofreading', 'Financial Documentation', 'Budget Planning ', 'Resource Management', name='member_skills')),
               nullable=False,
               existing_server_default=sa.text("'{}'::member_skills[]"))
    op.create_table('messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('messages_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('messages_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_project_id'), 'messages', ['project_id'], unique=False)
    # ### end Alembic commands ###
