"""modify member status

Revision ID: d285b0db8028
Revises: 218ba28275df
Create Date: 2026-05-15 18:00:22.985044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd285b0db8028'
down_revision: Union[str, Sequence[str], None] = '218ba28275df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('redistribution_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('suggestion_type', sa.Enum('SHARE', 'SPLIT', 'TRANSFER', 'RESCHEDULE', name='type'), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('expected_workload_after', sa.Text(), nullable=False),
    sa.Column('deadline_impact', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['project_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('member_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.UUID(), nullable=False),
    sa.Column('workload_points', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('workload_status', sa.Enum('OK', 'UNDERUTILIZED', 'OVERLOADED', name='member_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['project_members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('member_snapshots')
    op.drop_table('member_activities')
    op.drop_table('redistribution_recommendations')
    # ### end Alembic commands ###
