"""add project snapshot

Revision ID: e24a68c4387c
Revises: d285b0db8028
Create Date: 2026-05-15 19:53:50.211356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e24a68c4387c'
down_revision: Union[str, Sequence[str], None] = 'd285b0db8028'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=True),
    sa.Column('total_workload_points', sa.Integer(), nullable=False),
    sa.Column('avg_workload', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('progress_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('expected_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('expected_percentage', sa.Integer(), nullable=False),
    sa.Column('schedule_variance', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('workload_balance', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('imbalance_severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity'), nullable=False),
    sa.Column('health_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_snapshots')
    # ### end Alembic commands ###
