"""dunno

Revision ID: e7d08bd91fa0
Revises: 867fd347455f
Create Date: 2026-08-19 01:23:54.454636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e7d08bd91fa0'
down_revision: Union[str, Sequence[str], None] = '867fd347455f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assigned_members', 'role')
    op.alter_column('tasks', 'project_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'project_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.add_column('assigned_members', sa.Column('role', postgresql.ENUM('LEADER', 'MEMBER', name='role'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
