"""add relationship and cascade throughout all the models

Revision ID: f10c5c819256
Revises: 809bc169e710
Create Date: 2026-05-19 00:57:35.354560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f10c5c819256'
down_revision: Union[str, Sequence[str], None] = '809bc169e710'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('assigned_members_task_id_fkey'), 'assigned_members', type_='foreignkey')
    op.create_foreign_key(None, 'assigned_members', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('member_activities_member_id_fkey'), 'member_activities', type_='foreignkey')
    op.create_foreign_key(None, 'member_activities', 'project_members', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('member_snapshots_member_id_fkey'), 'member_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'member_snapshots', 'project_members', ['member_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('peer_evaluations_task_id_fkey'), 'peer_evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'peer_evaluations', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_members_project_id_fkey'), 'project_members', type_='foreignkey')
    op.create_foreign_key(None, 'project_members', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('redistribution_recommendations_project_id_fkey'), 'redistribution_recommendations', type_='foreignkey')
    op.create_foreign_key(None, 'redistribution_recommendations', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('supertasks_project_id_fkey'), 'supertasks', type_='foreignkey')
    op.create_foreign_key(None, 'supertasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_comments_task_id_fkey'), 'task_comments', type_='foreignkey')
    op.create_foreign_key(None, 'task_comments', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_contents_task_id_fkey'), 'task_contents', type_='foreignkey')
    op.create_foreign_key(None, 'task_contents', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_relations_task_id_fkey'), 'task_relations', type_='foreignkey')
    op.drop_constraint(op.f('task_relations_related_to_fkey'), 'task_relations', type_='foreignkey')
    op.create_foreign_key(None, 'task_relations', 'tasks', ['related_to'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_relations', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_submissions_task_id_fkey'), 'task_submissions', type_='foreignkey')
    op.create_foreign_key(None, 'task_submissions', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_tag_tag_id_fkey'), 'task_tag', type_='foreignkey')
    op.drop_constraint(op.f('task_tag_task_id_fkey'), 'task_tag', type_='foreignkey')
    op.create_foreign_key(None, 'task_tag', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_tag', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('tasks_project_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_project_id_fkey'), 'tasks', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'task_tag', type_='foreignkey')
    op.drop_constraint(None, 'task_tag', type_='foreignkey')
    op.create_foreign_key(op.f('task_tag_task_id_fkey'), 'task_tag', 'tasks', ['task_id'], ['id'])
    op.create_foreign_key(op.f('task_tag_tag_id_fkey'), 'task_tag', 'tags', ['tag_id'], ['id'])
    op.drop_constraint(None, 'task_submissions', type_='foreignkey')
    op.create_foreign_key(op.f('task_submissions_task_id_fkey'), 'task_submissions', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'task_relations', type_='foreignkey')
    op.drop_constraint(None, 'task_relations', type_='foreignkey')
    op.create_foreign_key(op.f('task_relations_related_to_fkey'), 'task_relations', 'tasks', ['related_to'], ['id'])
    op.create_foreign_key(op.f('task_relations_task_id_fkey'), 'task_relations', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'task_contents', type_='foreignkey')
    op.create_foreign_key(op.f('task_contents_task_id_fkey'), 'task_contents', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'task_comments', type_='foreignkey')
    op.create_foreign_key(op.f('task_comments_task_id_fkey'), 'task_comments', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'supertasks', type_='foreignkey')
    op.create_foreign_key(op.f('supertasks_project_id_fkey'), 'supertasks', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'redistribution_recommendations', type_='foreignkey')
    op.create_foreign_key(op.f('redistribution_recommendations_project_id_fkey'), 'redistribution_recommendations', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'project_members', type_='foreignkey')
    op.create_foreign_key(op.f('project_members_project_id_fkey'), 'project_members', 'projects', ['project_id'], ['id'])
    op.drop_constraint(None, 'peer_evaluations', type_='foreignkey')
    op.create_foreign_key(op.f('peer_evaluations_task_id_fkey'), 'peer_evaluations', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(None, 'member_snapshots', type_='foreignkey')
    op.create_foreign_key(op.f('member_snapshots_member_id_fkey'), 'member_snapshots', 'project_members', ['member_id'], ['id'])
    op.drop_constraint(None, 'member_activities', type_='foreignkey')
    op.create_foreign_key(op.f('member_activities_member_id_fkey'), 'member_activities', 'project_members', ['member_id'], ['id'])
    op.drop_constraint(None, 'assigned_members', type_='foreignkey')
    op.create_foreign_key(op.f('assigned_members_task_id_fkey'), 'assigned_members', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###
