"""update member snapshot

Revision ID: f52b925590ab
Revises: e7d08bd91fa0
Create Date: 2026-08-24 01:52:24.031869

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "f52b925590ab"
down_revision: Union[str, Sequence[str], None] = "e7d08bd91fa0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_snapshots", sa.Column("snapshot_date", sa.Date(), nullable=False)
    )
    op.create_unique_constraint(
        "uq_member_snapshot_date", "member_snapshots", ["member_id", "snapshot_date"]
    )
    op.drop_column("member_snapshots", "total_workload_points")
    op.drop_column("member_snapshots", "created_at")
    op.execute("ALTER TYPE member_status RENAME VALUE 'OK' TO 'NORMAL'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "member_snapshots",
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "member_snapshots",
        sa.Column(
            "total_workload_points",
            sa.NUMERIC(precision=10, scale=2),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_constraint("uq_member_snapshot_date", "member_snapshots", type_="unique")
    op.drop_column("member_snapshots", "snapshot_date")
    op.execute("ALTER TYPE member_status RENAME VALUE 'NORMAL' TO 'OK'")
    # ### end Alembic commands ###
