"""Change member.skills to list of Skills

Revision ID: fd2f444f6e50
Revises: e8f1a2b3c4d5
Create Date: 2026-09-18 03:29:32.093868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fd2f444f6e50'
down_revision: Union[str, Sequence[str], None] = 'e8f1a2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_project_created'), table_name='messages')
    op.drop_index(op.f('ix_messages_project_id'), table_name='messages')
    op.drop_table('messages')

    # Change skills from single enum to array of enums
    # First convert to array (this will turn NULL skills into ARRAY[NULL])
    op.alter_column('project_members', 'skills',
               existing_type=postgresql.ENUM('Backend Development', 'Frontend Development', 'Mobile Development', 'IOT Development', 'Database Design', 'System Architecture', 'UI/UX Design', 'Testing and Quality Assurance', 'Literature Review', 'Data Collection', 'Survey and Questionnaire Design', 'Interview and Observation', 'Data Analysis', 'Technical Writing', 'Documentation', 'Diagram and Modeling', 'Editing and Proofreading', 'Financial Documentation', 'Budget Planning ', 'Resource Management', name='member_skills'),
               type_=postgresql.ARRAY(postgresql.ENUM('Backend Development', 'Frontend Development', 'Mobile Development', 'IOT Development', 'Database Design', 'System Architecture', 'UI/UX Design', 'Testing and Quality Assurance', 'Literature Review', 'Data Collection', 'Survey and Questionnaire Design', 'Interview and Observation', 'Data Analysis', 'Technical Writing', 'Documentation', 'Diagram and Modeling', 'Editing and Proofreading', 'Financial Documentation', 'Budget Planning ', 'Resource Management', name='member_skills')),
               nullable=True,
               postgresql_using='ARRAY[skills]')  # Keep nullable for now during conversion
    # Now fix any NULL elements in the arrays (convert ARRAY[NULL] to ARRAY['Backend Development'])
    op.execute("UPDATE project_members SET skills = ARRAY['Backend Development'::member_skills] WHERE skills IS NULL OR array_position(skills, NULL) IS NOT NULL")

    # Finally, make the column NOT NULL
    op.alter_column('project_members', 'skills',
               existing_type=postgresql.ENUM('Backend Development', 'Frontend Development', 'Mobile Development', 'IOT Development', 'Database Design', 'System Architecture', 'UI/UX Design', 'Testing and Quality Assurance', 'Literature Review', 'Data Collection', 'Survey and Questionnaire Design', 'Interview and Observation', 'Data Analysis', 'Technical Writing', 'Documentation', 'Diagram and Modeling', 'Editing and Proofreading', 'Financial Documentation', 'Budget Planning ', 'Resource Management', name='member_skills'),
               type_=postgresql.ARRAY(postgresql.ENUM('Backend Development', 'Frontend Development', 'Mobile Development', 'IOT Development', 'Database Design', 'System Architecture', 'UI/UX Design', 'Testing and Quality Assurance', 'Literature Review', 'Data Collection', 'Survey and Questionnaire Design', 'Interview and Observation', 'Data Analysis', 'Technical Writing', 'Documentation', 'Diagram and Modeling', 'Editing and Proofreading', 'Financial Documentation', 'Budget Planning ', 'Resource Management', name='member_skills')),
               nullable=False,
               postgresql_using='ARRAY[skills]')  # Make non-nullable after cleaning

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # First make sure we can handle the conversion by dealing with NULLs and empty arrays
    # Set NULL values to a default single-element array
    op.execute("UPDATE project_members SET skills = ARRAY['Backend Development'::member_skills] WHERE skills IS NULL")
    op.execute("UPDATE project_members SET skills = ARRAY['Backend Development'::member_skills] WHERE array_length(skills, 1) = 0")
    op.execute("UPDATE project_members SET skills = ARRAY['Backend Development'::member_skills] WHERE skills[1] IS NULL")
    # Now convert array to single enum by taking the first element
    op.alter_column('project_members', 'skills',
               existing_type=postgresql.ARRAY(postgresql.ENUM('Backend Development', 'Frontend Development', 'Mobile Development', 'IOT Development', 'Database Design', 'System Architecture', 'UI/UX Design', 'Testing and Quality Assurance', 'Literature Review', 'Data Collection', 'Survey and Questionnaire Design', 'Interview and Observation', 'Data Analysis', 'Technical Writing', 'Documentation', 'Diagram and Modeling', 'Editing and Proofreading', 'Financial Documentation', 'Budget Planning ', 'Resource Management', name='member_skills')),
               type_=postgresql.ENUM('Backend Development', 'Frontend Development', 'Mobile Development', 'IOT Development', 'Database Design', 'System Architecture', 'UI/UX Design', 'Testing and Quality Assurance', 'Literature Review', 'Data Collection', 'Survey and Questionnaire Design', 'Interview and Observation', 'Data Analysis', 'Technical Writing', 'Documentation', 'Diagram and Modeling', 'Editing and Proofreading', 'Financial Documentation', 'Budget Planning ', 'Resource Management', name='member_skills'),
               nullable=True,
               postgresql_using='skills[1]')
    op.create_table('messages',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('messages_project_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_id'], ['users.id'], name=op.f('messages_sender_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('messages_pkey'))
    )
    op.create_index(op.f('ix_messages_project_id'), 'messages', ['project_id'], unique=False)
    op.create_index(op.f('ix_messages_project_created'), 'messages', ['project_id', 'created_at'], unique=False)
    # ### end Alembic commands ###