"""add supertask relationship in task

Revision ID: fe31c4846b26
Revises: 3bc9225d3779
Create Date: 2026-10-04 14:25:31.838576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fe31c4846b26'
down_revision: Union[str, Sequence[str], None] = '3bc9225d3779'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('supertasks', 'deadline')
    op.add_column('tasks', sa.Column('supertask_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'supertasks', ['supertask_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'supertask_id')
    op.add_column('supertasks', sa.Column('deadline', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
